name: DeployBlog
on:
  push:
    branches:
    # Blog 分支有 push 行为时就触发这个 action
      - Blog 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          PUBLISH_DIR: ./public
        

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: -rltgoDzvO --delete
            SOURCE: ./public/
            PORT: ${{ secrets.PORT }}
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME}}
            TARGET: ${{ secrets.PATH }}
