name: DeployBlog
on:
  push:
    branches:
    # Blog 分支有 push 行为时就触发这个 action
      - Blog 

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
        
      
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true
      
      - name: Build Hugo
        run: hugo --minify
        
      - name: Deploy
        uses: burnett01/rsync-deployments@5.2
        env:
          switches: -avzr --delete
          path: ./public
          remote_path: ${{ secrets.PATH }}
          remote_host: ${{ secrets.HOST }}
          remote_port: 1971
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
