name: DeployBlog
on:
  push:
    branches:
    # Blog 分支有 push 行为时就触发这个 action
      - Blog 

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
        
      
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true
      
      - name: Build Hugo
        run: hugo --minify
        
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
         ARGS: "-rltgoDzvO"
         SOURCE: "public/"
         REMOTE_HOST: 106.52.17.191
         REMOTE_USER: root
         REMOTE_PORT: 2222
         TARGET: /www/wwwroot/note.yxzi.xyz/
