name: DeployBlog
on:
  push:
    branches:
    # Blog 分支有 push 行为时就触发这个 action
      - Blog 

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          extended: true
      
      - name: Build Hugo
        run: hugo --minify
        
      - name: Deploy To Server
        uses: yeshan333/rsync-deploy-action@v1.0.0
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            SOURCE: ./public/
            ARGS: "-rltgoDzvO"
            PORT: ${{ secrets.PORT }}
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME}}
            TARGET: ${{ secrets.PATH }}
