name: DeployBlog
on:
  push:
    branches:
    # Blog 分支有 push 行为时就触发这个 action
      - Blog 

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
            node-version: '10.x'
      
           
      - name: Install Rsync 
        run: npm install rsync -g
        
     # - name: Setup Hugo
      #  uses: peaceiris/actions-hugo@v2
      #  with:
     #     hugo-version: '0.91.2'
      #    extended: true
      
      #- name: Build Hugo
      #  run: hugo --minify
        
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            SOURCE: ./public/
            ARGS: "-rltgoDzvO"
            PORT: ${{ secrets.PORT }}
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: ${{ secrets.USERNAME}}
            TARGET: ${{ secrets.PATH }}
