name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main # main 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_KEEP_DEPLOY }}
          PUBLISH_REPOSITORY: XavierJiezou/xavierjiezou.github.io
          BRANCH: gh-pages
          PUBLISH_DIR: ./public

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: -rltgoDzvO --delete
            SOURCE: ./public/
            REMOTE_HOST: ghgxj.xyz
            REMOTE_USER: root
            TARGET: /www/wwwroot/ghgxj.xyz/
